<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\AI\Platform\Serializer;

use Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor;
use Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor;
use Symfony\Component\PropertyInfo\PropertyInfoExtractor;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Mapping\ClassDiscriminatorFromClassMetadata;
use Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory;
use Symfony\Component\Serializer\Mapping\Loader\AttributeLoader;
use Symfony\Component\Serializer\Normalizer\ArrayDenormalizer;
use Symfony\Component\Serializer\Normalizer\BackedEnumNormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

class StructuredOutputSerializer extends Serializer
{
    /*
     * Custom serializer made to deserialize StructuredOutput.
     *
     * Since field name are generated by the `Symfony\AI\Platform\Contract\JsonSchema\Factory`
     * without using the serializer (and the serializer metadata/attributes), we have to ignore them
     * again when deserializing the data by not passing `classMetadataFactory` to ObjectNormalizer.
     */
    public function __construct()
    {
        $classMetadataFactory = new ClassMetadataFactory(new AttributeLoader());
        $discriminator = new ClassDiscriminatorFromClassMetadata($classMetadataFactory);
        $propertyInfo = new PropertyInfoExtractor([], [new PhpDocExtractor(), new ReflectionExtractor()]);

        $normalizers = [
            new BackedEnumNormalizer(),
            new ObjectNormalizer(
                propertyTypeExtractor: $propertyInfo,
                classDiscriminatorResolver: $discriminator,
            ),
            new ArrayDenormalizer(),
        ];

        parent::__construct($normalizers, [new JsonEncoder()]);
    }
}
